site_name: Tasker for Ricoh Theta

nav:
    - Home: 'index.md'
    - Deep-Linking URL: 'http-req-tut.md'
    - Run Tasker Commands: 'tasker-tut.md'
    - Add Commands to Homescreen: 'homescreen-tut.md'
    - Exporting Task as a Link: 'export-tut.md'

extra:
  analytics: 
    provider: google
    property: G-QWVFHF19M8
    
theme:
  name: material
  palette:
    primary: 'light green'
    accent: 'lime'
  logo: images/icon/green-logo-192x192.png
  favicon: images/icon/favicon-16x16.png
